version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8.10-management
    hostname: localhost
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    build:
      context: ./redis
    restart: always
    ports:
      - 6379:6379
